### PR TITLE
Adds the Hand of God

### PR DESCRIPTION
**Pull request by TheCarlSaganExpress**
The Hand of God was never really finished and it was only given a simple HELP command. Although, the original documentation states that the Hand of God would have been used for turning avatars into a pile of smoking cinder. After consulting with Randy it was then decided that the Hand of God would be given the implementation that it deserves! The only feature that is currently missing from the Hand of God is the ability to turn an avatar into a ghost, rather than outright killing them. 

**Using the Hand of God**

- You must possess a god tool in order to use the Hand of God

- To summon the Hand of God, type in the letter 'g' followed by the victim's name.

- E.x. you would type "gjason" in the god tool prompt to smite the user named Jason.

hand of god pic

### CODE REVIEW

**Comment by frandallfarmer** [comment]
WOW! Thanks for this. Could you make one change for me? You are not supposed to see the top edge of the hand. Could you move it up so that it always appears to emerge from the top of the screen?

Or create a cloud object as well so it seems to emerge from the cloud.. (that's probably harder...)
I can't wait to see this in action!

**Comment by frandallfarmer** [comment]
While I'm commenting, I'd like a godsay command to have the hand utter stuff that the oracle types....

**Comment by TheCarlSaganExpress** [comment]
@frandallfarmer Your wish is my command!

**Comment by TheCarlSaganExpress** [comment]
Sorry for the delay, I meant to have these changes up sooner but a few things came up. But now you can speak as the Hand of God!

**Comment by frandallfarmer** [comment]
Looks good enough to put in production! Great work -  I can't wait to try it!

**Pull request merged**
