### PR TITLE
Use object().name() to identify bureaucrats

### PR DESCRIPTION
**Pull request by pedrouran**
2 files are affected, bureaucrat.java and Downtown_6i.json

### CODE REVIEW

**Comment by frandallfarmer** [comment]
Thank you for making these work. PR accepted as first minimally functional version! Congratulations.

One piece of minor feedback - what was originally two cases "2" and "3" have been combined into a single case - operational/administrative functions, not just "complaints" - it'd be good to cleanup the code (remove the hanging HELP messages, and rename "complaints" to something else, like "MessageCratbot" or something like that.

**Comment by pedrouran** [comment]
Hello Randy,

It is a honor to contribute with you in this wonderful project.

If I well understand, do you want me to change the label under the desktop of bureaucrat 3 "Complaints" to "Messages" inside the City Hall, and change the name of bureaucrat 3 for "MessageCratbot"?

Best regards.

**Comment by frandallfarmer** [comment]
Yes. Please rename it to MessageCrat or similar to more properly reflect the utility of your new 3 mode design replacing the old 4 mode one. While doing that, it'd be good to fix the help command as we discussed on the slack.

**Comment by pedrouran** [comment]
Hello Randy,

Ok I'm going to reserach about help messages.

**Comment by pedrouran** [comment]
Hello Randy,

It has not been easy for me, I have had to create a new class for each bureaucrat, since help messages go by object class help_messages[HabitatClass()], and I couldn't find any other way to discriminate between bureaucrats other than to create its own object class.

This modification affects to 12 files, and one of them dissapear (class bureaucrat.java), since it divides in 3 (PropertyCrabot, LicensesCrabot and MessagesCrabot.java), one class for each bureaucrat.

Well, it is already finished, and working in my server but I want to test it deeply.

Best regards

**Comment by frandallfarmer** [comment]
Please do not take this approach. Let's arrange to speak in person about how to sort your improvements back into the original file.

**Comment by pedrouran** [comment]
Hello Randy,

Okay, no problem, I look forward to seeing a better way.

**Comment by pedrouran** [comment]
Hello Randy,

First of all I want to thank you for spend your time explaining me the structure of the project. 

My daughter has been very excited all the afternoon because she has met you :), she only has 10 years old, but she plays C64 games in real C64 machine almost before learrn to talk. And she plays Neohabitat too. She knows the history of Habitat, and she knows you by pictures and videos, so it has been like meet to a Rock Star. ( I also have to admit that for me too)

Well, I've come a little bit, and now I can intercept F7 messages, so now I need to differentiate between bureaucrats. I will investigate with the constructor variables as you said to me.

Sorry for my poor english level. I don`t use to speak in english, and it cost me to maintain a conversation and follow the source code at same time (because I think in spanish, and I have to do a simultaneous translation... to much work for my neurons). But I can well understand you more or less.

Best regards.

**Comment by pedrouran** [comment]
Hello again Randy,

It is done, really it was very simple, I can access to object().name() from HELP function in bureaucrat.java class, so differenciate between bureaucrats is as simple than this:

    public void HELP(User from) {
	String BureacratName = object().name().toLowerCase();
	send_reply_msg(from, "I am: " + BureacratName);
    }

And now when I hitting F7  I can show customs messages for each bureaucrats.

image

**Comment by pedrouran** [comment]
Hello Randy,

I attach you the bureaucrats F7 help messages for each one, so you fill them to your liking.

Please keep the long of the strngs because it fits the maximun of characters allowed (3 complete lines), and send it back to me, to do a Pull Request against your repo.

Thank you very much.

    public void HELP(User from) {
	String BureacratName = object().name().toLowerCase();
        switch(BureacratName) { 
            case "propertycrabot":
		send_reply_msg(from, "PROPERTY BUREAUCRAT: TALK sends your request to the bureaucracy.  Please be sure this is the right bureaucrat.");
                break;
            case "licensescrabot":
		send_reply_msg(from, "LICENSES BUREAUCRAT: TALK sends your request to the bureaucracy.  Please be sure this is the right bureaucrat.");
                break;
            case "complaintscrabot":
		send_reply_msg(from, "COMPLAINTS BUREAUCRAT: TALK sends your request to the bureaucracy.  Please be sure this is the right bureaucrat.");
                break;
	}
		
    }

**Pull request merged**
