### PR TITLE
Adds Grenade.java and minor refactor for Weapon, Constants, and HabitatMod

### PR DESCRIPTION
**Pull request by TheCarlSaganExpress**
grenade pic
Thanks to the helpful advice from Steve and Randy the grenade is finally in Habitat!  Also, methods from Weapon have been moved into HabitatMod.

### CODE REVIEW

**Comment by frandallfarmer** [comment]
That's pretty impressive work. I do see what looks like a bug:
"send_reply_msg(curAvatar.elko_user(), noid, "PULLPIN_SUCCESS", success);"
Looks to be sent multiple times (it's inside a loop.) Also, I think you don't want to send that after you've killed the pin-pulling avatar if they are dead. Do you send it so late because the client tries to delete the grenade?

**Comment by TheCarlSaganExpress** [comment]
I felt the same way about the "PULLPIN_SUCCESS" message, but it needs to be sent late even after avatar death because the grenade thread would get interrupted and break. The other "PULLPIN_SUCCESS" message is used so that it finishes the "DO" command and allows the avatar to thrown and put down a live grenade as they please. If that sounds confusing and weird it's because it is. But I'll do some more testing and see if I can get that message out of that loop.

Also, the "EXPLODE_$" message is actually responsible for attempting to delete the grenade.

**Comment by TheCarlSaganExpress** [comment]
I did some additional testing and the success message does need to stay inside the loop. Without that line  only the avatar who performed the original "DO" command on the grenade will be teleported upon death. Other avatars in the region would get a blinking cursor and have to reboot their client.

**Comment by frandallfarmer** [comment]
That's very odd. We must discuss. reply_ messages are designed to go only to those who have outstanding requests. I understand it seems to function properly, but your description is inconsistent with all message flow design for every other class. I need to understand how a "reply" is going to each client who didn't make a request before I can accept this PR. Perahaps you @steve and I can get on a call...

**Comment by frandallfarmer** [comment]
Looks good! Thanks Jason!

**Pull request merged**
